# Generated by Django 2.2.24 on 2023-12-11 08:37

import phonenumbers
from django.db import migrations


def convert_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        pure_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(pure_number):
            flat.owner_pure_phone = pure_number
            flat.save()



def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20231211_1424'),
    ]

    operations = [
        migrations.RunPython(convert_phone_number, move_backward)
    ]
