# Generated by Django 2.2.24 on 2023-12-11 08:37

from django.db import migrations
import phonenumbers


def convert_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        pure_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.owner_pure_phone = pure_number
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20231211_1424'),
    ]

    operations = [
        migrations.RunPython(convert_phone_number)
    ]
